### ISSUE TITLE
a.espncdn.com

### ISSUE THREAD

**Issue by p1r473** [pirat28/IHateTracker#10]
This is the ESPN CDN (Entertainment and Sports Programming Network Content Delivery Network)
Blocking this breaks ESPN
ex.  https://www.espn.com/nba/story/_/id/29747523/three-game-5s-set-wednesday-postponed-bucks-decision-boycott

**Comment by pirat28** [comment]
Sorry for not reacting fast.
I will delete ist from the list.

**Comment by p1r473** [comment]
Thanks
