### ISSUE TITLE
Possibility to create a host file?

### ISSUE THREAD

**Issue by gallegonovato** [pirat28/IHateTracker#12]
Good afternoon:

First of all thank you for your hard work, effort, your time and for your lists.

I would like to ask you a question if I may. 

I don't know if it would be possible to create a host file, to be able to use your work also with Adaway?

If you would be so kind to take my consideration and if you can do it, I would be grateful.

Receive a warm embrace and thank you for your time.

**Comment by pirat28** [comment]
Hi,
sorry, I just use the pi-hole and this list was made to use with the pi-hole.
