### ISSUE TITLE
static.wikia.nocookie.net

### ISSUE THREAD

**Issue by p1r473** [pirat28/IHateTracker#13]
This hosts static Wiki content
Example:
Images on https://pirates.fandom.com/wiki/Black_Pearl
https://static.wikia.nocookie.net/pirates/images/6/62/Black_Pearl_infobox.png/revision/latest/scale-to-width-down/350?cb=20171110192901
https://static.wikia.nocookie.net/pirates/images/4/4c/Blackpearlsig.png/revision/latest/scale-to-width-down/130?cb=20111017033033

**Comment by pirat28** [comment]
Sorry for the late replay...
--> done :)
Thanks
